config/routes.rb
Rails.application.routes.draw do
  resources :sessions

  resources :users do
    resources :posts do
      resources :comments
    end
  end

  resources :likes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :likes, as: :likeable, dependent: :destroy
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  belongs_to :friend_with_user, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, -> { order(created_at: :desc) }
  belongs_to :user
  validates :content, length: { minimum: 10}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :comments
  has_many :posts, -> { order(created_at: :desc) }
  has_many :friends, class_name: 'Friend', foreign_key: 'user_id'
  has_many :friends_with, class_name: 'Friend', foreign_key: 'friend_with_user_id'
  has_many :likes, as: :likeable
  has_one_attached :avatar
  # validation start from here
  validates :first_name, presence: true
  validates :first_name, format: { with: /[a-zA-Z]+/, message: 'only allows letters' }
  validates :middle_name, presence: true
  validates :middle_name, format: { with: /[a-zA-Z]+/, message: 'only allows letters' }
  validates :last_name, presence: true
  validates :last_name, format: { with: /[a-zA-Z]+/, message: 'only allows letters' }
  validates :gender, presence: true
  validates :gender, inclusion: { in: %w[Male Female Transgender], message: "%{value} is not a valid" }
  # validates :date_of_birth, presence: true
  validates :relationship, inclusion: { in: %w[Married Single Live-In Complicated], message: "%{value} is not a valid" }
  validates :bio, length: { maximum: 150 }
  validates :emails, presence: true
end

# email uniqueness need to rethink

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :require_login
  helper_method :current_user

  def check_login
    redirect_to user_path(current_user) if session.include? :user_id
  rescue ActionController::RedirectBackError
    redirect_to root_path
  end

  def require_login
    redirect_to new_session_path unless session.include? :user_id
  end

  private

  def current_user
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end

  def user_info
    @user = User.find_by(id: params[:user_id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :comment_data

  def comment_data
    @user = User.find_by(id: params[:user_id])
    @post = @user.posts.find_by(id: params[:post_id])
    @comment = params[:id] ? @post.comments.find_by(id: params[:id]) : Comment.new
  end

  def update
    unless @comment&.update(comment_params)
      flash[:comment_error] = 'Error- please try to update an comment again.'
      redirect_to user_path(@user)
    end

    redirect_to edit_user_post_comment_path(@user, @post, @comment)
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params) do |elem|
      elem.user_id = params[:user_id]
      elem.post_id = params[:post_id]
    end
    # need to ask is there diffrent way to do this
    flash[:comment_error] = 'Error- please try to update an comment again.' unless @comment.save
    redirect_to user_path(@user)
  end

  def destroy
    
    flash[:comment_error] = 'Error- please try to delete an Comment again.' unless @comment&.destroy

    redirect_to user_path(@user)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = likable_type_data.likes.find_by(user_id: params[:user_id])

    if @like
      @like.destroy
    else
      @like = likable_type_data.likes.create(user_id: params[:user_id])
    end

    redirect_to user_path(current_user)
  end

  private

  def likable_type_data
    if params[:post_id]
      Post.find_by(id: params[:post_id])
    else
      Comment.find_by(id: params[:comment_id])
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  
  def index
  end

  def sign_up
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :post_data

  def post_data
    @user = User.find_by(id: params[:user_id])
    @post = params[:id] ? @user.posts.find_by(id: params[:id]) : Post.new
  end

  def create
    @post = @user.posts.create(post_params)

    flash[:post_error] = 'Error- please try to update an post again.' if @post.invalid?
    if @post.valid?
      redirect_to edit_user_post_path(@user, @post)
    else
      redirect_to user_path(@user)
    end
  end

  def new
  end

  def edit
  end

  def update
    flash[:post_error] = 'Error- please try to update an post again.' unless @post&.update(post_params)

    redirect_to edit_user_post_path(@user, @post)
  end

  def destroy
    flash[:post_error] = 'Error- please try to delete an post again.' unless @post&.destroy

    redirect_to user_path(@user)
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  before_action :check_login, only: %i[new create]

  def create
    session_params = params.permit(:email, :password)
    @user = User.find_by(emails: session_params[:email])
    if @user&.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:notice] = 'Login is invalid!'
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been signed out!"
    redirect_to new_session_path
  end

  def new
    @user = User.new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  before_action :check_login, only: %i[new create]

  def index
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    @user.avatar.attach(params[:avatar])
    if @user.valid? && @user.update(user_edit_params)
      session[:user_id] = @user.id
    else
      flash[:error] = 'Error- please try to update an account again.'
    end

    redirect_to @user
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:error] = 'Error- please try to create an account again.'
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :middle_name, :last_name, :gender, :relationship, :emails, :password, :avatar)
  end

  def user_edit_params
    params.require(:user).permit(:first_name, :middle_name, :last_name, :gender, :relationship, :emails, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_avatar(user, size = 40)
    if user.avatar.attached?
      user.avatar
    else
      gravatar_image_url(user.emails, size: size)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment-container">
  <div class="small-image-box">
      <%= image_tag user_avatar(comment.user ,40), width: "40px", height: "40px"  %>
  </div>
  <div class="comment-container_content">
    <div class="comment-container_content-text">
      <div>
        <%= link_to "#{comment.user.first_name} #{comment.user.middle_name} #{comment.user.last_name}", user_path(comment.user) %>
      </div>
      <div>
        <%= comment.content %>
      </div>
    </div>
    <div class="comment-container_content-like">
      <%= button_to likes_path, remote: true, pa rams: { user_id: current_user.id, comment_id: comment.id }, class: "like_button"   do %>
        <div>
          <img height="18" role="presentation" src="data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 16 16'%3e%3cdefs%3e%3clinearGradient id='a' x1='50%25' x2='50%25' y1='0%25' y2='100%25'%3e%3cstop offset='0%25' stop-color='%2318AFFF'/%3e%3cstop offset='100%25' stop-color='%230062DF'/%3e%3c/linearGradient%3e%3cfilter id='c' width='118.8%25' height='118.8%25' x='-9.4%25' y='-9.4%25' filterUnits='objectBoundingBox'%3e%3cfeGaussianBlur in='SourceAlpha' result='shadowBlurInner1' stdDeviation='1'/%3e%3cfeOffset dy='-1' in='shadowBlurInner1' result='shadowOffsetInner1'/%3e%3cfeComposite in='shadowOffsetInner1' in2='SourceAlpha' k2='-1' k3='1' operator='arithmetic' result='shadowInnerInner1'/%3e%3cfeColorMatrix in='shadowInnerInner1' values='0 0 0 0 0 0 0 0 0 0.299356041 0 0 0 0 0.681187726 0 0 0 0.3495684 0'/%3e%3c/filter%3e%3cpath id='b' d='M8 0a8 8 0 00-8 8 8 8 0 1016 0 8 8 0 00-8-8z'/%3e%3c/defs%3e%3cg fill='none'%3e%3cuse fill='url(%23a)' xlink:href='%23b'/%3e%3cuse fill='black' filter='url(%23c)' xlink:href='%23b'/%3e%3cpath fill='white' d='M12.162 7.338c.176.123.338.245.338.674 0 .43-.229.604-.474.725a.73.73 0 01.089.546c-.077.344-.392.611-.672.69.121.194.159.385.015.62-.185.295-.346.407-1.058.407H7.5c-.988 0-1.5-.546-1.5-1V7.665c0-1.23 1.467-2.275 1.467-3.13L7.361 3.47c-.005-.065.008-.224.058-.27.08-.079.301-.2.635-.2.218 0 .363.041.534.123.581.277.732.978.732 1.542 0 .271-.414 1.083-.47 1.364 0 0 .867-.192 1.879-.199 1.061-.006 1.749.19 1.749.842 0 .261-.219.523-.316.666zM3.6 7h.8a.6.6 0 01.6.6v3.8a.6.6 0 01-.6.6h-.8a.6.6 0 01-.6-.6V7.6a.6.6 0 01.6-.6z'/%3e%3c/g%3e%3c/svg%3e" width="18">
          <span><%= comment.likes.count if comment.likes.count > 0 %></span>
        </div>
      <% end %>
    </div>
  </div>
  <div>
    <a class="nav-link" href="#" id="navbarEditComment" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <svg viewBox="0 0 20 20" width="1em" height="1em" class="a8c37x1j ms05siws hwsy1cff b7h9ocf4 em6zcovv jnigpg78 odw8uiq3"><g fill-rule="evenodd" transform="translate(-446 -350)"><path d="M458 360a2 2 0 1 1-4 0 2 2 0 0 1 4 0m6 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0m-12 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0"></path></g></svg>
    </a>
    
    <ul class="dropdown-menu" aria-labelledby="navbarEditComment" >
      <li>
        <%= link_to "Edit Comment", edit_user_post_path(comment.user, comment.post, comment), class: "dropdown-item"  %>
      </li>
      <li>  
        <%= link_to "Delete Comment", [comment.user, comment.post, comment], method: :delete, class: "dropdown-item", 
              data: { confirm: "Are you sure?" }  %>
      </li>
    </ul>
  </div>
</div>

app/views/comments/_form.html.erb
<% if flash[:comment_error] %>
    <p><%= flash[:comment_error] %></p>
<% end %>

<div class="comment-container">
  <div class="small-image-box">
      <%= image_tag user_avatar(current_user, 40), width: "40px", height: "40px"  %>
  </div>
  
  <div class="comment-container_new">
    <%= form_with model: [ user, post, comment ]  do |form| %>
      <div>
        <%= form.text_field :content, placeholder: "Write a comment...", class: "comment_input" %>
        <% user.errors.full_messages_for(:content).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <%= form.submit class: "hide" %>
    <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<%= render 'form', {user: @user, post: @post, comment: @comment} %>

<%= link_to "Back", user_path(@user) %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<%= render 'comments/form', { user: current_user, post: post, comment: Comment.new } %>

app/views/friends/_form.html.erb
<% if flash[:friend_error] %>
    <p><%= flash[:friend_error] %></p>
<% end %>

<section>
  <h1>Add a Friend</h1>
  <%= form_with url: friends_path do |form| %>
    <%= form.text_field :email %>
    <%= form.submit “Create” %>
  <% end %>
</section>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/login/index.html.erb
<h1>Login</h1>

app/views/posts/_form.html.erb
<% if flash[:post_error] %>
    <p><%= flash[:post_error] %></p>
<% end %>

<%= form_with model: [ user, post ]  do |form| %>
  <div>
    <%= form.text_area :content, placeholder: "What's on your mind", class: "post_input" %>
    <% post.errors.full_messages_for(:content).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <%= form.submit "Post", class: "post_btn" %>
<% end %>

app/views/posts/_post.html.erb
<div class="post-container__card">
  <div class="post-container__card-header">
    <div class="small-image-box">
    <%= image_tag user_avatar(post.user ,40), width: "40px", height: "40px"  %>
    </div>
    <div class="post_container-userinfo">
    <%= link_to "#{post.user.first_name} #{post.user.middle_name} #{post.user.last_name}", user_path(post.user) %>
    </div>

    <div>      
      <a class="nav-link" href="#" id="navbarEditPost" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <svg viewBox="0 0 20 20" width="1em" height="1em" class="a8c37x1j ms05siws hwsy1cff b7h9ocf4 em6zcovv jnigpg78 odw8uiq3"><g fill-rule="evenodd" transform="translate(-446 -350)"><path d="M458 360a2 2 0 1 1-4 0 2 2 0 0 1 4 0m6 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0m-12 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0"></path></g></svg>
      </a>
      <ul class="dropdown-menu" aria-labelledby="navbarEditPost" >
          <li> 
            <%= link_to "Edit Post", edit_user_post_path(post.user, post), class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to "Delete Post", [post.user, post], method: :delete, class: "dropdown-item", 
                  data: { confirm: "Are you sure?" }  %>
          </li>
      </ul>
    </div>
  </div>

  <div class="post_container-content">
    <%= post.content %>
  </div>
  <div class="post-container-social-state">
    <div class="post-container-social-state-like" >
      <span>
        <%= button_to likes_path, remote: true, class: "like_button", params: { user_id: current_user.id, post_id: post.id }  do %>
          <img height="18" role="presentation" src="data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 16 16'%3e%3cdefs%3e%3clinearGradient id='a' x1='50%25' x2='50%25' y1='0%25' y2='100%25'%3e%3cstop offset='0%25' stop-color='%2318AFFF'/%3e%3cstop offset='100%25' stop-color='%230062DF'/%3e%3c/linearGradient%3e%3cfilter id='c' width='118.8%25' height='118.8%25' x='-9.4%25' y='-9.4%25' filterUnits='objectBoundingBox'%3e%3cfeGaussianBlur in='SourceAlpha' result='shadowBlurInner1' stdDeviation='1'/%3e%3cfeOffset dy='-1' in='shadowBlurInner1' result='shadowOffsetInner1'/%3e%3cfeComposite in='shadowOffsetInner1' in2='SourceAlpha' k2='-1' k3='1' operator='arithmetic' result='shadowInnerInner1'/%3e%3cfeColorMatrix in='shadowInnerInner1' values='0 0 0 0 0 0 0 0 0 0.299356041 0 0 0 0 0.681187726 0 0 0 0.3495684 0'/%3e%3c/filter%3e%3cpath id='b' d='M8 0a8 8 0 00-8 8 8 8 0 1016 0 8 8 0 00-8-8z'/%3e%3c/defs%3e%3cg fill='none'%3e%3cuse fill='url(%23a)' xlink:href='%23b'/%3e%3cuse fill='black' filter='url(%23c)' xlink:href='%23b'/%3e%3cpath fill='white' d='M12.162 7.338c.176.123.338.245.338.674 0 .43-.229.604-.474.725a.73.73 0 01.089.546c-.077.344-.392.611-.672.69.121.194.159.385.015.62-.185.295-.346.407-1.058.407H7.5c-.988 0-1.5-.546-1.5-1V7.665c0-1.23 1.467-2.275 1.467-3.13L7.361 3.47c-.005-.065.008-.224.058-.27.08-.079.301-.2.635-.2.218 0 .363.041.534.123.581.277.732.978.732 1.542 0 .271-.414 1.083-.47 1.364 0 0 .867-.192 1.879-.199 1.061-.006 1.749.19 1.749.842 0 .261-.219.523-.316.666zM3.6 7h.8a.6.6 0 01.6.6v3.8a.6.6 0 01-.6.6h-.8a.6.6 0 01-.6-.6V7.6a.6.6 0 01.6-.6z'/%3e%3c/g%3e%3c/svg%3e" width="18">
        <% end %>
      </span>
      <span class="social-state-like-count" >
        <%= post.likes.count %>
      </span>
    </div>
    <div class="post-container-social-state-comment">
      <span><%= "#{post.comments.count} comments" if  post.comments.count > 0 %></span>
    </div>
  </div>
  <div class="post_container-footer">
    <div>
      <%= render 'comments/form', { user: post.user, post: post, comment: Comment.new } %>
      <%= render post.comments %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Posts</h1>

<%= render 'form', { user: @user, post: @post } %>

<%= link_to "Back", user_path(@user) %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Edit Posts</h1>

<%= render 'form', { user: @user, post: @post } %>

<%= link_to "Back", user_path(@user) %>

app/views/users/_form.html.erb
<div class="signup-container_box" >
  <%= form_with model: user  do |form| %>
  <div class="signup-name-box">
    <div class="input-box" >
      <%= form.text_field :first_name, placeholder: "First Name" %>
      <% user.errors.full_messages_for(:first_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    <div class="input-box" >
      <%= form.text_field :middle_name, placeholder: "Middle Name" %>
      <% user.errors.full_messages_for(:middle_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="input-box">
      <%= form.text_field :last_name, placeholder: "Last Name" %>
      <% user.errors.full_messages_for(:last_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  </div>

    <div class="input-box">
      <%= form.text_field :emails, placeholder: "Email Address", class: 'emails' %>
      <% user.errors.full_messages_for(:emails).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

  <% if !current_user %>
    <div class="input-box" >
      <%= form.label :password %>
      <%= form.password_field :password %><br>
      <% user.errors.full_messages_for(:password).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
    
    <div class="input-box">
    <%= form.label :relationship %><br>
    <%= form.select :relationship, ['Married', 'Single', 'Live-In', 'Complicated'], default: 'public' %>
    <% user.errors.full_messages_for(:relationship).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="input-box">
    <%= form.label :gender %><br>
    <%= form.select :gender, ['Male', 'Female', 'Transgender'], default: 'public' %>
    <% user.errors.full_messages_for(:gender).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    <div>
      <%= form.file_field :avatar %>
    </div>
    <div>
      <%= form.submit current_user ? "Update" : "Sign Up", class: "signup_btn" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<section  class="signup-container" >
  <%= render 'form', { user: current_user } %>
</section>

app/views/users/index.html.erb
<h1>Post you content</h1>

app/views/users/new.html.erb
<section  class="signup-container" >
  <header class="signup-header">
    <% if flash[:error] %>
      <h1><%= flash[:error] %></h1>
    <% else %>
      <h1>Sign Up</h1>
      <span>It's quick and easy.</span>
    <% end %>
  </header>

  <%= render 'form', { user: @user } %>
</section>

app/views/users/show.html.erb
<% if flash[:error] %>
  <h1><%= flash[:error] %></h1>
<% end %>
<h1><%= @user.first_name + " " + @user.middle_name + " " + @user.last_name %></h1>

<main class="timeline-container" >
  <div class="timeline-container-box">
    <%= render 'posts/form', { user: current_user, post: Post.new } %>    
    <%= render @user.posts %>
  </div>
</main>